[2023-11-29 15:20:20,282] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_district_daily manual__2023-11-29T15:18:25.802002+00:00 [queued]>
[2023-11-29 15:20:20,293] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_district_daily manual__2023-11-29T15:18:25.802002+00:00 [queued]>
[2023-11-29 15:20:20,294] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 15:20:20,295] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-11-29 15:20:20,296] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 15:20:20,313] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_district_daily> on 2023-11-29 15:18:25.802002+00:00
[2023-11-29 15:20:20,328] {standard_task_runner.py:52} INFO - Started process 5741 to run task
[2023-11-29 15:20:20,332] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'd_1_etl_FinalProject', 'insert_district_daily', 'manual__2023-11-29T15:18:25.802002+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/d_1_etl_FinalProject.py', '--cfg-path', '/tmp/tmpev_1_rzf', '--error-file', '/tmp/tmp0_vef7d6']
[2023-11-29 15:20:20,341] {standard_task_runner.py:80} INFO - Job 104: Subtask insert_district_daily
[2023-11-29 15:20:20,454] {task_command.py:369} INFO - Running <TaskInstance: d_1_etl_FinalProject.insert_district_daily manual__2023-11-29T15:18:25.802002+00:00 [running]> on host 92ab6769debf
[2023-11-29 15:20:20,549] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=d_1_etl_FinalProject
AIRFLOW_CTX_TASK_ID=insert_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-29T15:18:25.802002+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-29T15:18:25.802002+00:00
[2023-11-29 15:20:20,688] {logging_mixin.py:115} INFO - Error: relation "dim_case" does not exist
LINE 1: SELECT id, status FROM dim_case
                               ^
[2023-11-29 15:20:20,689] {python.py:173} INFO - Done. Returned value was: None
[2023-11-29 15:20:20,706] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=d_1_etl_FinalProject, task_id=insert_district_daily, execution_date=20231129T151825, start_date=20231129T152020, end_date=20231129T152020
[2023-11-29 15:20:20,765] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-29 15:20:20,985] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
