[2023-11-29 15:28:56,969] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_district_daily manual__2023-11-29T15:18:25.802002+00:00 [queued]>
[2023-11-29 15:28:56,981] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_district_daily manual__2023-11-29T15:18:25.802002+00:00 [queued]>
[2023-11-29 15:28:56,982] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 15:28:56,983] {taskinstance.py:1357} INFO - Starting attempt 3 of 3
[2023-11-29 15:28:56,984] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 15:28:57,000] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_district_daily> on 2023-11-29 15:18:25.802002+00:00
[2023-11-29 15:28:57,014] {standard_task_runner.py:52} INFO - Started process 5925 to run task
[2023-11-29 15:28:57,017] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'd_1_etl_FinalProject', 'insert_district_daily', 'manual__2023-11-29T15:18:25.802002+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/d_1_etl_FinalProject.py', '--cfg-path', '/tmp/tmpx6n4hd9z', '--error-file', '/tmp/tmpildpdidl']
[2023-11-29 15:28:57,018] {standard_task_runner.py:80} INFO - Job 105: Subtask insert_district_daily
[2023-11-29 15:28:57,251] {task_command.py:369} INFO - Running <TaskInstance: d_1_etl_FinalProject.insert_district_daily manual__2023-11-29T15:18:25.802002+00:00 [running]> on host 92ab6769debf
[2023-11-29 15:28:57,513] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=d_1_etl_FinalProject
AIRFLOW_CTX_TASK_ID=insert_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-29T15:18:25.802002+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-29T15:18:25.802002+00:00
[2023-11-29 15:28:57,897] {logging_mixin.py:115} INFO - Error: relation "district_daily" does not exist
LINE 2:                 INSERT INTO district_daily (district_id, cas...
                                    ^
[2023-11-29 15:28:57,898] {python.py:173} INFO - Done. Returned value was: None
[2023-11-29 15:28:57,909] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=d_1_etl_FinalProject, task_id=insert_district_daily, execution_date=20231129T151825, start_date=20231129T152856, end_date=20231129T152857
[2023-11-29 15:28:57,954] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-29 15:28:57,983] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
