[2023-11-29 14:25:47,091] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_province_daily scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2023-11-29 14:25:47,103] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_province_daily scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2023-11-29 14:25:47,104] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 14:25:47,104] {taskinstance.py:1357} INFO - Starting attempt 7 of 7
[2023-11-29 14:25:47,105] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 14:25:47,124] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_province_daily> on 2023-11-28 00:00:00+00:00
[2023-11-29 14:25:47,136] {standard_task_runner.py:52} INFO - Started process 4559 to run task
[2023-11-29 14:25:47,143] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'd_1_etl_FinalProject', 'insert_province_daily', 'scheduled__2023-11-28T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/d_1_etl_FinalProject.py', '--cfg-path', '/tmp/tmpgawr4on8', '--error-file', '/tmp/tmpl2d_ircg']
[2023-11-29 14:25:47,145] {standard_task_runner.py:80} INFO - Job 97: Subtask insert_province_daily
[2023-11-29 14:25:47,232] {task_command.py:369} INFO - Running <TaskInstance: d_1_etl_FinalProject.insert_province_daily scheduled__2023-11-28T00:00:00+00:00 [running]> on host 92ab6769debf
[2023-11-29 14:25:47,340] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=d_1_etl_FinalProject
AIRFLOW_CTX_TASK_ID=insert_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-28T00:00:00+00:00
[2023-11-29 14:25:47,343] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/d_1_etl_FinalProject.py", line 19, in insert_province_daily_func
    insert_province_daily_script.insert_province_daily(**kwargs)
AttributeError: module 'modules.insert_province_daily_script' has no attribute 'insert_province_daily'
[2023-11-29 14:25:47,362] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=d_1_etl_FinalProject, task_id=insert_province_daily, execution_date=20231128T000000, start_date=20231129T142547, end_date=20231129T142547
[2023-11-29 14:25:47,380] {standard_task_runner.py:97} ERROR - Failed to execute job 97 for task insert_province_daily (module 'modules.insert_province_daily_script' has no attribute 'insert_province_daily'; 4559)
[2023-11-29 14:25:47,403] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-29 14:25:47,434] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
