[2023-11-29 15:48:15,957] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_province_daily manual__2023-11-29T15:18:25.802002+00:00 [queued]>
[2023-11-29 15:48:15,967] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_province_daily manual__2023-11-29T15:18:25.802002+00:00 [queued]>
[2023-11-29 15:48:15,968] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 15:48:15,968] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2023-11-29 15:48:15,969] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 15:48:15,984] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_province_daily> on 2023-11-29 15:18:25.802002+00:00
[2023-11-29 15:48:15,992] {standard_task_runner.py:52} INFO - Started process 6358 to run task
[2023-11-29 15:48:16,012] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'd_1_etl_FinalProject', 'insert_province_daily', 'manual__2023-11-29T15:18:25.802002+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/d_1_etl_FinalProject.py', '--cfg-path', '/tmp/tmpe3r258dp', '--error-file', '/tmp/tmpfpre26zt']
[2023-11-29 15:48:16,013] {standard_task_runner.py:80} INFO - Job 112: Subtask insert_province_daily
[2023-11-29 15:48:16,117] {task_command.py:369} INFO - Running <TaskInstance: d_1_etl_FinalProject.insert_province_daily manual__2023-11-29T15:18:25.802002+00:00 [running]> on host 92ab6769debf
[2023-11-29 15:48:16,209] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=d_1_etl_FinalProject
AIRFLOW_CTX_TASK_ID=insert_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-29T15:18:25.802002+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-29T15:18:25.802002+00:00
[2023-11-29 15:48:16,278] {logging_mixin.py:115} INFO - Error: insert or update on table "province_daily" violates foreign key constraint "province_daily_province_id_fkey"
DETAIL:  Key (province_id)=(3204) is not present in table "dim_province".
[2023-11-29 15:48:16,279] {python.py:173} INFO - Done. Returned value was: None
[2023-11-29 15:48:16,298] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=d_1_etl_FinalProject, task_id=insert_province_daily, execution_date=20231129T151825, start_date=20231129T154815, end_date=20231129T154816
[2023-11-29 15:48:16,329] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-29 15:48:16,433] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
