[2023-11-29 16:17:35,055] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_province_daily manual__2023-11-29T15:18:25.802002+00:00 [queued]>
[2023-11-29 16:17:35,066] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_province_daily manual__2023-11-29T15:18:25.802002+00:00 [queued]>
[2023-11-29 16:17:35,066] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 16:17:35,067] {taskinstance.py:1357} INFO - Starting attempt 5 of 5
[2023-11-29 16:17:35,068] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 16:17:35,085] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_province_daily> on 2023-11-29 15:18:25.802002+00:00
[2023-11-29 16:17:35,113] {standard_task_runner.py:52} INFO - Started process 6992 to run task
[2023-11-29 16:17:35,115] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'd_1_etl_FinalProject', 'insert_province_daily', 'manual__2023-11-29T15:18:25.802002+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/d_1_etl_FinalProject.py', '--cfg-path', '/tmp/tmp0_tpeos_', '--error-file', '/tmp/tmp8351z6bw']
[2023-11-29 16:17:35,117] {standard_task_runner.py:80} INFO - Job 114: Subtask insert_province_daily
[2023-11-29 16:17:35,192] {task_command.py:369} INFO - Running <TaskInstance: d_1_etl_FinalProject.insert_province_daily manual__2023-11-29T15:18:25.802002+00:00 [running]> on host 92ab6769debf
[2023-11-29 16:17:35,285] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=d_1_etl_FinalProject
AIRFLOW_CTX_TASK_ID=insert_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-29T15:18:25.802002+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-29T15:18:25.802002+00:00
[2023-11-29 16:17:35,476] {logging_mixin.py:115} INFO - Error: relation "dim_case" does not exist
LINE 1: SELECT id, status FROM dim_case
                               ^
[2023-11-29 16:17:35,477] {python.py:173} INFO - Done. Returned value was: None
[2023-11-29 16:17:35,492] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=d_1_etl_FinalProject, task_id=insert_province_daily, execution_date=20231129T151825, start_date=20231129T161735, end_date=20231129T161735
[2023-11-29 16:17:35,530] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-29 16:17:35,563] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
